// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD54D2oAgWbDVJXq_4MNHcSJDrhqvlNSGQ',
    appId: '1:410680540370:web:845c382dfaf16147e9410b',
    messagingSenderId: '410680540370',
    projectId: 'pepo-s-wings-and-more',
    authDomain: 'pepo-s-wings-and-more.firebaseapp.com',
    storageBucket: 'pepo-s-wings-and-more.firebasestorage.app',
    measurementId: 'G-RQ2ZCXCB2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlCnqbiVu2w3VDcq_qA1ggcLQMImGxVTY',
    appId: '1:410680540370:android:7566bc5ad48c849ae9410b',
    messagingSenderId: '410680540370',
    projectId: 'pepo-s-wings-and-more',
    storageBucket: 'pepo-s-wings-and-more.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABzxMxVPS5HDwivD1AItnyIEz4r8Ihs8w',
    appId: '1:410680540370:ios:1102ff3f9afddbdfe9410b',
    messagingSenderId: '410680540370',
    projectId: 'pepo-s-wings-and-more',
    storageBucket: 'pepo-s-wings-and-more.firebasestorage.app',
    iosBundleId: 'com.example.peposwings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABzxMxVPS5HDwivD1AItnyIEz4r8Ihs8w',
    appId: '1:410680540370:ios:1102ff3f9afddbdfe9410b',
    messagingSenderId: '410680540370',
    projectId: 'pepo-s-wings-and-more',
    storageBucket: 'pepo-s-wings-and-more.firebasestorage.app',
    iosBundleId: 'com.example.peposwings',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD54D2oAgWbDVJXq_4MNHcSJDrhqvlNSGQ',
    appId: '1:410680540370:web:1c20f7fa41be05f6e9410b',
    messagingSenderId: '410680540370',
    projectId: 'pepo-s-wings-and-more',
    authDomain: 'pepo-s-wings-and-more.firebaseapp.com',
    storageBucket: 'pepo-s-wings-and-more.firebasestorage.app',
    measurementId: 'G-5M5Z7HR8ZJ',
  );

}